version: '3.0'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true      
    ports:
      - "3000:3000"
    volumes:
      - .:/app
     